{% set name = "QSS" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get('VERSION_FROM_GIT_TAG') }}

source:
  path: .. # checked out repo instead of main repo branch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - pip
    - python
    - scipy
    - numpy
    - qdldl-python
    - cvxpy
    - matplotlib

test:
  imports:
    - qss
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cvxgrp/qss
  license: Apache
  license_family: Apache
  license_file: LICENSE
  summary: QSS Quadratic-Separable Solver
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - lukevolpatti
    - Thistleman
    - pluflou
