{% set name = "QSS" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get('VERSION_FROM_GIT_TAG') }}

source:
  git_url: https://github.com/cvxgrp/qss

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install -e ./ -r requirements.txt "

requirements:
  host:
    - pip
    - python
    - scipy
    - numpy
    - qdldl-python
    - cvxpy
    - matplotlib

  run:
    - pip
    - python
    - scipy
    - numpy
    - qdldl-python
    - cvxpy
    - matplotlib

about:
  home: https://github.com/cvxgrp/qss
  license: BSD
  license_family: BSD
  license_file:
  summary: QSS Quadratic-Seperable Solver
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - lukevolpatti
    - Thistleman
