name: Main Test
on: 
  push:
    branches:
      - master
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

          - name: Install Python
            uses: actions/setup-python@v3

          - name: Install Dependencies
            run: | 
              sudo pip install -r requirements.txt
              pip install -e .

# Current unit test is not consistent. Occasionally fails despite usually passing. Needs to be fixed.
          - name: Run Unit Tests
            run: python -m pytest --import-mode=append tests/